package com.urja.motoservice.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SERVICE_REQUEST".
 */
public class ServiceRequest {

    private Long id;
    private String groupname;
    private String code;
    private String desc;
    private String vehiclegroup;
    private String carnumber;

    public ServiceRequest() {
    }

    public ServiceRequest(Long id) {
        this.id = id;
    }

    public ServiceRequest(Long id, String groupname, String code, String desc, String vehiclegroup, String carnumber) {
        this.id = id;
        this.groupname = groupname;
        this.code = code;
        this.desc = desc;
        this.vehiclegroup = vehiclegroup;
        this.carnumber = carnumber;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getGroupname() {
        return groupname;
    }

    public void setGroupname(String groupname) {
        this.groupname = groupname;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public String getVehiclegroup() {
        return vehiclegroup;
    }

    public void setVehiclegroup(String vehiclegroup) {
        this.vehiclegroup = vehiclegroup;
    }

    public String getCarnumber() {
        return carnumber;
    }

    public void setCarnumber(String carnumber) {
        this.carnumber = carnumber;
    }

}
