package com.urja.motoservice.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "VALID_VEHICLE".
 */
public class ValidVehicle {

    private Long id;
    private String carType;
    private String code;
    private String downloadPath;
    private String path;

    public ValidVehicle() {
    }

    public ValidVehicle(Long id) {
        this.id = id;
    }

    public ValidVehicle(Long id, String carType, String code, String downloadPath, String path) {
        this.id = id;
        this.carType = carType;
        this.code = code;
        this.downloadPath = downloadPath;
        this.path = path;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCarType() {
        return carType;
    }

    public void setCarType(String carType) {
        this.carType = carType;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getDownloadPath() {
        return downloadPath;
    }

    public void setDownloadPath(String downloadPath) {
        this.downloadPath = downloadPath;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

}
