package com.urja.motoservice.database.dao;

import android.database.sqlite.SQLiteDatabase;

import com.urja.motoservice.database.ServiceRequest;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig serviceRequestDaoConfig;

    private final ServiceRequestDao serviceRequestDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        serviceRequestDaoConfig = daoConfigMap.get(ServiceRequestDao.class).clone();
        serviceRequestDaoConfig.initIdentityScope(type);

        serviceRequestDao = new ServiceRequestDao(serviceRequestDaoConfig, this);

        registerDao(ServiceRequest.class, serviceRequestDao);
    }
    
    public void clear() {
        serviceRequestDaoConfig.getIdentityScope().clear();
    }

    public ServiceRequestDao getServiceRequestDao() {
        return serviceRequestDao;
    }

}
